# Site settings
title: Michael Drogalis
email: mjd3089@rit.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: MichaelDrogalis
github_username:  MichaelDrogalis

kramdown:
  input: GFM

# Build settings
markdown: kramdown

